#!/usr/bin/env bash
set -o pipefail
set -e

have(){
	command -v >/dev/null 2>&1 "$1" || {
		printf >&2 'Required program "%s" not found\n' "$1"
		exit 1
	}
}

have mandoc
have xml

mandoc -Thtml -Ofragment "$@" \
| xml -q tr --html --omit-decl  "$(dirname "$0")/man2html.xslt" - \
| awk '
	/<h1/      { flag = 1 }
	/<\/body>/ { flag = 0 }
	flag
'
